### ISSUE TITLE
Not working with WSL

### ISSUE THREAD

**Issue by jeansordes** [graphile/starter#179]
When I run `yarn setup` I get the following result :

```
$ yarn setup
yarn run v1.22.4
$ yarn && node ./scripts/setup.js
[1/4] Resolving packages...
success Already up-to-date.
? What would you like to call your database? graphile_starter
? What's the hostname of your database server (include :port if it's not the default :5432)? localhost
? Please enter a superuser connection string to the database server (so we can drop/create the 'graphile_starter' and 'graphile_starter_shadow' databases) - 
IMPORTANT: it must not be a connection to the 'graphile_starter' database itself, instead try 'template1'. postgres://postgres:postgres@localhost:5432/postgr
es
? We're going to drop (if necessary):

  - database graphile_starter
  - database graphile_starter_shadow
  - database role graphile_starter_visitor (cascade)
  - database role graphile_starter_authenticator (cascade)
  - database role graphile_starter Yes
Installing or reinstalling the roles and database...
graphile-migrate: dropped database 'graphile_starter'
graphile-migrate: recreated database 'graphile_starter'
Schema updated

graphile-migrate: Running migration '000001.sql'
graphile-migrate: 1 committed migrations executed
graphile-migrate[shadow]: dropped database 'graphile_starter_shadow'
graphile-migrate[shadow]: recreated database 'graphile_starter_shadow'
Schema updated

graphile-migrate[shadow]: Running migration '000001.sql'
Error: Command failed: if [ "$IN_TESTS" != "1" ]; then ./scripts/dump-db; fi
./scripts/dump-db: line 18: syntax error: unexpected end of file

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'if [ "$IN_TESTS" != "1" ]; then ./scripts/dump-db; fi',
  stdout: '',
  stderr: './scripts/dump-db: line 18: syntax error: unexpected end of file\n'
}
Error: Process exited with status '1' (running 'yarn db reset --shadow --erase')
    at runSync (/mnt/c/Users/jean/Documents/tifod/graphile-starter/scripts/lib/run.js:31:13)
    at main (/mnt/c/Users/jean/Documents/tifod/graphile-starter/scripts/setup.js:331:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by benjie** [comment]
Help adding WSL compatibility would be welcome. Currently the Docker mode is the recommended approach on Windows.

Once done; it'd be nice to add some GitHub Actions that check that we don't break Windows compatibility.

**Comment by tlebon** [comment]
i get the same error on mac currently.

**Comment by benjie** [comment]
@tlebon Are you using an alternative shell? Try using bash... Which it should use automatically:

https://github.com/graphile/starter/blob/46134bf2d127ae46661edaf80a811a4332e9bc9d/%40app/db/scripts/dump-db#L1

To be clear, by "the same error" you mean this:

```
./scripts/dump-db: line 18: syntax error: unexpected end of file
```

?

**Comment by tlebon** [comment]
the issue here is the pg_dump command. For some reason it is not available on your (and my) postgres instance. 
(Perhaps someone else can comment on this situation, i am a postgreSQL noobie unfortunately. using postgres on mac)

inside of @app/db/scripts/dump-db i commented out from line 10 on and the setup completed without errors. 

@benjie oh yeah i use zsh, i suppose that is the issue then. 
by same error, i mean i get that exact output as he pasted above.

**Comment by tlebon** [comment]
switching to bash didnt change anything 🤷‍♂️

**Comment by benjie** [comment]
pg_dump comes bundled with Postgres. We use the PG_DUMP envvar in Docker to tell pg_dump to run on the Postgres Docker container: 

https://github.com/graphile/starter/blob/58699dd1b759a3dd8e6f50cdc0622979f037e897/docker/scripts/yarn-setup.js#L29-L34

But the error you have is a syntax error, which indicates different from `pg_dump` not being available on your system.

**Comment by tlebon** [comment]
so I had installed postgresql via the postgresql installer and not thru brew. this changed the location of the `pg_dump` command from `/usr/bin/env `to `/Library/PostgreSQL/12/scripts/` or so. So running `pg_dump` obviously didnt work in the starter since the command didnt exist in that location. 

installing via homebrew fixed this. removing the offending code fixes this. running in docker i would assume would also fix it.

**Comment by benjie** [comment]
(Also fixing your `$PATH` would probably have fixed it too.)

**Comment by ilhamsa1** [comment]
I previously got the same error, it happened because I installed graphile-starter in the windows directory
(d:/graphile-starter)

```

graphile-migrate[shadow]: Running migration '000001.sql'
Error: Command failed: if [ "$IN_TESTS" != "1" ]; then ./scripts/dump-db; fi
/usr/bin/env: 'bash\r': No such file or directory

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'if [ "$IN_TESTS" != "1" ]; then ./scripts/dump-db; fi',
  stdout: '',
  stderr: "/usr/bin/env: 'bash\\r': No such file or directory\n"
}
```


, but when I installed it in the wsl root directory, graphile-starter was running fine

`cd ~/dev/graphile-starter`
```

graphile-migrate[shadow]: recreated database 'gp_starter_shadow'
Schema updated

graphile-migrate[shadow]: Running migration '000001.sql'
graphile-migrate[shadow]: 1 committed migrations executed


____________________________________________________________


✅ Setup success

🚀 To get started, run:

  yarn start


🙏 Please support our Open Source work:
     https://graphile.org/sponsor

____________________________________________________________

$ lerna run setup
Done in 192.37s.

```

**Comment by benjie** [comment]
The error you have there suggests that you're using Windows line endings (`\r\n`), but only _parsing_ Unix line endings (`\n`) and thus the line `#!/usr/bin/env bash\r\n` was being interpretted as `#!/usr/bin/env bash\r` rather than `#!/usr/bin/env bash`. So I think it's a git line-ending issue rather than something specifically related to the Starter. Did you configure your Git to automatically change the line endings?

**Comment by MichaelJCole** [comment]
I got this to work on WSL2 using the Postgres packaged using apt:

`sudo apt install postgresql postgresql-contrib git curl build-essential`

I wrote up my notes as an evaluation, which you can see here: 
 https://docs.google.com/document/d/1DyXpd3vbS0l9V4Iud5INnLNPl6bUB_CG7oPn4R1M_D4/edit?usp=sharing

**Comment by benjie** [comment]
@MichaelJCole Great notes! Given you're on Windows if you fancied checking out Windows native development (rather than WSL) I'd really appreciate an approval on https://github.com/graphile/starter/pull/203 if it works for you?

**Comment by MichaelJCole** [comment]
@benjie Hmmmm...  That's a whole other kettle of fish.  I looked through the commits, but didn't grok it well enough to have an opinion.  I have a rule about not learning "things I need to know only once", so I haven't gotten into native web dev on Windows.  I know it is a thing for .Net developers.  Lacking that, here are some notes about Windows support from projects I've used recently:

[Quasar has some notes for building Electron apps on windows](https://quasar.dev/quasar-cli/developing-electron-apps/preparation#A-note-for-Windows-Users)
[Feathers has notes in code coverage and might be interesting as an implementation reference](https://docs.feathersjs.com/guides/basics/testing.html#test-database-setup)
[Meteor did it with something called Chocolatey](https://chocolatey.org/how-chocolatey-works)

There is a [Linux dev setup for Unreal Engine](https://docs.unrealengine.com/en-US/Platforms/Linux/BeginnerLinuxDeveloper/SettingUpAnUnrealWorkflow/index.html) but it's not supported by Epic Games, so I went with Windows.  

For web dev, I'm sticking with Ubuntu.  Combining Ubuntu20.04 (on WSL) and Docker for Windows made a fast Kubernetes environment for developing micro-services.  I could write up my notes on how I set that up for an article if you like.  

I think the Linux workflow is better supported across the JS ecosystem and that's why Microsoft did WSL.  But like I said, I'm ignorant of how Windows-first users are working with Node.

**Comment by benjie** [comment]
Fair enough :+1: I tend to aim for the built packages to run on Windows, but I tend not to worry about supporting Windows in development. I develop Graphile Worker on Ubuntu 20.04 (native) FWIW (and, rarely, macOS).

**Comment by benjie** [comment]
(Also I was more wondering if you could actually run it rather than review the PR itself.)

**Comment by benjie** [comment]
Closing thanks to @MichaelJCole's report :+1:
