### ISSUE TITLE
User Privacy: better defaults (?) [security]

### ISSUE THREAD

**Issue by MP70** [graphile/starter#191]
Currently you can call userByUsername without auth and get the full user details back. This includes PII such as full name, user photo ect. This also tells us if the user has a password(or oauth by implication), if they are an admin, and if their email address is verified none of which are good for security. I would generally consider this a bug as from what I can see there is no need to expose this info publicly and the user is not warned this info is public (although I note some of it is commented as 'publicly facing' in the schema).

Logically I think exposing this information to the user themself only is the most correct thing to do by default (unless it is clear to the user otherwise), if it is clear to the user then at most shared with owners/admins of a company they are members of.

**Comment by benjie** [comment]
This is a concern that your own applications can implement, depending on what makes sense for _your_ use case. It is **also** your responsibility to add terms of use, privacy policy, etc; these are ways in which you may notify your users. It should be noted that Graphile Starter is **not** an application in itself, so assertions such as "from what I can see there is no need to expose this info publicly" are missing the point because the functionality that would decide whether that's needed or not does not exist yet.

I've built Graphile Starter with the defaults that are most useful for services that I plan to build, and the type of things that my clients build. For you to be able to invite someone to your organization it's convenient to be able to search by username like on GitHub, Trello, etc and see their name and avatar in response. Further you cannot invite someone to an organization until their email is verified, so verifying their email is expected to be something all users do very soon after creating their account, so this is not PII - it should be true for everyone with an account over a few minutes old. Whether someone being an admin or not should be exposed is really application preference, you could wrap the resolver for that and return null for everyone who isn't you, just like we do with whether someone has a password or not:

![Uploading Screenshot_20200811_152849.png…]()


As you'll already know security and convenience are a trade-off, and the trade-offs I've made in the starter are the ones I've chosen after many years of building applications. You are of course welcome to take this as a starting point and change the trade-offs to match your own requirements.

> This also tells us if the user has a password(or oauth by implication)

No it doesn't; this is only visible to the current user.
